name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_examples:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install mandatory tools
        run: |
          git clone --depth=1 https://github.com/apple-cross-toolchain/rules_applecross.git /tmp/rules_applecross
          sudo /tmp/rules_applecross/tools/install-mandatory-tools.sh
          rm -rf /tmp/rules_applecross
      - name: Create .netrc
        run: |
          cat > ~/.netrc <<EOF
          machine api.github.com
          login ${{ secrets.APPLE_SDKS_GH_PAT_USER }}
          password ${{ secrets.APPLE_SDKS_GH_PAT_PASSWORD }}
          EOF
          chmod 600 ~/.netrc
      - name: Fetch toolchain and set developer dir
        run: |
          bazel fetch @apple_cross_toolchain//:all
          DEVELOPER_DIR="$(bazel info output_base)/external/+apple_cross_toolchain+apple_cross_toolchain/Xcode.app/Contents/Developer"
          sudo xcode-select -s "$DEVELOPER_DIR"
      - run: bazel build @MBProgressHUD//:MBProgressHUDFramework
      - uses: actions/upload-artifact@v4
        with:
          name: MBProgressHUDFramework
          path: bazel-bin/external/MBProgressHUD/MBProgressHUDFramework.zip
