name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_examples:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: |
          cat > ~/.netrc <<EOF
          machine api.github.com
          login ${{ secrets.SDKS_USER }}
          password ${{ secrets.SDKS_PASSWORD }}
          EOF
          chmod 600 ~/.netrc
          sed -i 's|SDKS_URL|${{ secrets.SDKS_URL }}|g' MODULE.bazel
      - run: bazel build @MBProgressHUD//:MBProgressHUDFramework
      - uses: actions/upload-artifact@v4
        with:
          name: MBProgressHUDFramework
          path: bazel-bin/external/MBProgressHUD/MBProgressHUDFramework.zip
