name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_examples:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: |
          cat > ~/.netrc <<EOF
          machine api.github.com
          login ${{ secrets.SDKS_USER }}
          password ${{ secrets.SDKS_PASSWORD }}
          EOF
          chmod 600 ~/.netrc
          sed -i 's|SDKS_URL|${{ secrets.SDKS_URL }}|g' MODULE.bazel
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - run: >-
          bazel build @MBProgressHUD//:MBProgressHUDFramework
          --remote_cache=${{ secrets.BAZEL_REMOTE_CACHE }}
          --google_default_credentials
          --remote_upload_local_results=true
          --remote_download_toplevel
      - uses: actions/upload-artifact@v4
        with:
          name: MBProgressHUDFramework
          path: bazel-bin/external/+http_archive+MBProgressHUD/MBProgressHUDFramework.zip
